### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Kaezon/spacestation13-java-clone#1]
```
If it's not I would like to export this to GitHub and continue development.
```

Original issue reported on code.google.com by `NGupto...@gmail.com` on 17 Jun 2015 at 3:32

**Comment by Kaezon** [comment]
Project is in suspended animation. I'm cleaning this up so other interested parties can take a look and contribute if they like.
Once I clear my schedule up a bit, I'll start looking into updating the code.
